plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.knowyourmoney'
    compileSdk 35

    defaultConfig {
        applicationId 'com.example.knowyourmoney.v2'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }

    signingConfigs {
        release {
            storeFile file("KnowYourMoney-release.jks")
            storePassword System.getenv("KEYSTORE_PASSWORD")
            keyAlias System.getenv("KEY_ALIAS")
            keyPassword System.getenv("KEY_PASSWORD")
            storeType "PKCS12"
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }
}

dependencies {
}
